language: python
os: linux
dist: xenial

cache: pip

install:
  - pip install -r requirements.txt

jobs:
  fast_finish: true

  include:
    # Main run, tests build, RSS, and packaging
    - name: "3.7 Makefile Build"
      python: 3.7
      env: COMMAND="make sphinx -j$(nproc)"
      deploy:
        provider: script
        script: bash deploy.bash
        skip_cleanup: true
        on:
          branch: master
          repo: python/peps

    # Tests build on 3.7-dev
    - name: "3.7-dev Build Test"
      python: 3.7-dev
      env: COMMAND="make sphinx -j$(nproc)"

    # Tests build on 3.8
    - name: "3.8 Build Test"
      python: 3.8
      env: COMMAND="make sphinx -j$(nproc)"

    # Tests build on 3.8-dev
    - name: "3.8-dev Build Test"
      python: 3.8-dev
      env: COMMAND="make sphinx -j$(nproc)"

    # Tests build with Fail on Warning
    - name: "3.8 Fail on Warning"
      python: 3.8
      env:
        - COMMAND="make fail_on_warning -j$(nproc)"

# linkcheck takes far too long (upwards of an hour)
#    # Checks link references within PEPs
#    - name: "3.8 Check Links"
#      python: 3.8
#      env:
#        - COMMAND="make check_links -j$(nproc)"

  allow_failures:
    # Note test failure, but pass the build as a whole
    - name: "3.8 Fail on Warning"

#    # Check links can fail as it is dependent on external pages
#    - name: "3.8 Check Links"

script: $COMMAND